services:
  plusultra:
    build: .
    image: plusultra:latest
    pull_policy: never
    container_name: plusultra
    restart: unless-stopped
    ports:
      - "8675:8675"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - plusultra-data:/app/server/data
    environment:
      - PORT=8675

volumes:
  plusultra-data:
